name: fakestore
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  chopper: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^6.0.0-nullsafety.1
  http: ^0.13.4
  json_serializable: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  chopper_generator: ^4.0.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
